### ISSUE TITLE
Crash on Google Pixel device (OS- 8.1.0): Fatal signal 6 (SIGABRT), code -6 in tid 21161 

### ISSUE THREAD

**Issue by ssaxena0891** [red5pro/streaming-android#106]
Streaming is running fine on other devices I tested with OS Nougat but it starts crashing on Google Pixel device (OS- 8.1.0) when I start publishing a stream. Here is my stacktrace:

A/libc: invalid pthread_t 0x7b81ab95b0 passed to libc
01-04 15:12:56.672 20964-21161/com.****** A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 21161 (com.******), pid 20964 (com.******)
01-04 15:12:56.781 21224-21224/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-04 15:12:56.781 21224-21224/? A/DEBUG: Build fingerprint: 'google/sailfish/sailfish:8.1.0/OPM1.171019.011/4448085:user/release-keys'
01-04 15:12:56.781 21224-21224/? A/DEBUG: Revision: '0'
01-04 15:12:56.781 21224-21224/? A/DEBUG: ABI: 'arm64'
01-04 15:12:56.781 21224-21224/? A/DEBUG: pid: 20964, tid: 21161, name: com.******  >>> com.****** <<<
01-04 15:12:56.781 21224-21224/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
01-04 15:12:56.784 21224-21224/? A/DEBUG: Abort message: 'invalid pthread_t 0x7b81ab95b0 passed to libc'
01-04 15:12:56.784 21224-21224/? A/DEBUG:     x0   0000000000000000  x1   00000000000052a9  x2   0000000000000006  x3   0000000000000008
01-04 15:12:56.784 21224-21224/? A/DEBUG:     x4   0000000000000000  x5   0000000000000000  x6   0000000000000000  x7   0000000000000030
01-04 15:12:56.784 21224-21224/? A/DEBUG:     x8   0000000000000083  x9   46c2815602b47de6  x10  0000000000000000  x11  ffffffffffffffff
01-04 15:12:56.784 21224-21224/? A/DEBUG:     x12  0000000000000028  x13  0000000000000000  x14  0000000000000000  x15  00280e08ac5c0126
01-04 15:12:56.784 21224-21224/? A/DEBUG:     x16  00000060a3768fa8  x17  0000007c1b284430  x18  0000000000000000  x19  00000000000051e4
01-04 15:12:56.784 21224-21224/? A/DEBUG:     x20  00000000000052a9  x21  0000000000000083  x22  0000007b8089e000  x23  0000000000000000
01-04 15:12:56.784 21224-21224/? A/DEBUG:     x24  0000007b8068ee50  x25  0000007b7ff5c000  x26  0000007c1f6eda40  x27  0000000000000000
01-04 15:12:56.784 21224-21224/? A/DEBUG:     x28  0000007fe9da4af0  x29  0000007b80058390  x30  0000007c1b237a2c
01-04 15:12:56.785 21224-21224/? A/DEBUG:     sp   0000007b80058350  pc   0000007c1b237a4c  pstate 0000000060000000
01-04 15:12:56.787 21224-21224/? A/DEBUG: backtrace:
01-04 15:12:56.787 21224-21224/? A/DEBUG:     #00 pc 000000000001da4c  /system/lib64/libc.so (abort+112)
01-04 15:12:56.787 21224-21224/? A/DEBUG:     #01 pc 000000000006a18c  /system/lib64/libc.so (__pthread_internal_find(long)+184)
01-04 15:12:56.787 21224-21224/? A/DEBUG:     #02 pc 000000000006a1c8  /system/lib64/libc.so (pthread_join+56)
01-04 15:12:56.788 21224-21224/? A/DEBUG:     #03 pc 000000000022cf58  /data/app/com.******-JPdnv5QGtJP5d648SfZikQ==/lib/arm64/libred5streaming.so (uv_thread_join+24)
01-04 15:12:58.360 634-21069/? E/mm-camera: <ISP   ><ERROR> 227:

**Comment by beetlejesss** [comment]
Does this crash happen every time that you try to publish with this device?
Do you have any other devices with this same Android version? 
We will try to reproduce - I'm not sure if we have any 8.x devices in house though.
In the future, it is better to submit bugs to the Red5 Pro help desk - through https://red5pro.zendesk.com/hc/en-us/requests/new - so that we can track.  Thank you

**Comment by ssaxena0891** [comment]
Yes, it crashes every time on this device.
Currently its the only device I have with OS 8.x.
I will also try to arrange another 8.x device and will update its behaviour here. But for now I can provide you only these information.

**Comment by ssaxena0891** [comment]
Just verified. It crashes on other devices too with OS 8.x.

**Comment by beetlejesss** [comment]
Have you tried with the latest update to the SDK/testbed? We added some stability with the 4.4.0 release.

**Comment by ssaxena0891** [comment]
Yes, I updated my SDK to 4.4.0 and it stopped crashing. Thanks beetlejesss.

**Comment by beetlejesss** [comment]
Great to hear!  Thanks for the updates :)
