### ISSUE TITLE
Unable to publish stream with new Android version 4.6.0 in red5pro

### ISSUE THREAD

**Issue by MamtaBansal8** [red5pro/streaming-android#126]
![capture](https://user-images.githubusercontent.com/40568000/41850434-2857e478-78a2-11e8-8f42-3a39c0de416b.PNG)
Hi..
I am unable to publish stream by using android 4.6.0 version in red5pro server. It shows no client in debug info of stream. Please help me.

**Comment by HoldenMills** [comment]
Hello. Thanks for taking a look at Red5 Pro.

Please provide our support team with more information by submitting a ticket using this link: https://red5pro.zendesk.com/hc/en-us/requests/new.
Please make sure to provide additional details such as reproduction steps to speed up the process.

**Comment by beetlejesss** [comment]
@MamtaBansal8 publishing via the Emulator is not supported. You need a physical device with a camera. You should be able to use the Android emulator to subscribe however.

**Comment by MamtaBansal8** [comment]
I have already raised a ticket.But no response found

**Comment by MamtaBansal8** [comment]
@beetlejesss i have tried it on physical devices also. But its not working.

**Comment by MamtaBansal8** [comment]
@HoldenMills i am using this project "red5pro/streaming android" and I have changed the ip and sdk key. But its not working.

**Comment by HoldenMills** [comment]
I have searched through our support desk and was not able to find a ticket that matches your description. Perhaps it didn't go through? Please let me know the email you used to submit the ticket so that I can look it up. Otherwise, please try submitting a ticket again so that we can get all the information necessary: https://red5pro.zendesk.com/hc/en-us/requests/new

**Comment by MamtaBansal8** [comment]
Its pankaj.pundir1030@gmail.com through which the ticket is raised.

**Comment by xenione** [comment]
Hi,

I have the same issue. it help us if you post solution on this Thread.

**Comment by beetlejesss** [comment]
Make sure that you have port 8554 (default RTSP) open on your server. If you continue to have issues, please submit a ticket including device and server logs to https://red5pro.zendesk.com/hc/en-us/requests/new so someone from the helpdesk can help you directly.
