### ISSUE TITLE
Memory leaks on R5Stream

### ISSUE THREAD

**Issue by deyupopp** [red5pro/streaming-android#151]
Hello,

I did some profiling on the attached application with the Android Studio profiler and I noticed some memory leaks. The steps to reproduce are the following:
- run the project on a real device (as emulator is not recommended for profiling)
- start a profiling session with Android Studio profiler
- navigate to the subscribing activity, using the FloatingActionButton
- dismiss activity (e.g. using hardware back button)
- (optional) repeat last two steps several times
- when on the MainActivity, invoke several garbage collections using the profiler
- create a heap dump using the profiler

Notice that none of the StreamingActivity instances were deallocated, even though onDestroy was called. If you look at the instances of R5Stream in the heap dump, you will notice that they have 0 depth, meaning that they are kept alive by a root object (probably a JNI reference that was not disposed).
[Red5Pro 2.zip](https://github.com/red5pro/streaming-android/files/3207406/Red5Pro.2.zip)

**Comment by HoldenMills** [comment]
Hello. Thank you for looking into this for us and providing detailed reproduction steps. 

Normally the way we handle this kind of issue is through our support desk. We would really appreciate it if you could please take the time to fill out a ticket using this link:
https://red5pro.zendesk.com/hc/en-us/requests/new
That way we can better track and organize all the information needed.

Thanks!
