### ISSUE TITLE
Uploading apk/bundle error

### ISSUE THREAD

**Issue by zainkhalid91** [red5pro/streaming-android#170]
Hi! I am getting this error on google play store when uploading the apk/bundle.

Error
This release is not compliant with the Google Play 64-bit requirement

The following APKs or App Bundles are available to 64-bit devices, but they only have 32-bit native code: *3.

Include 64-bit and 32-bit native code in your app. Use the Android App Bundle publishing format to automatically ensure that each device architecture receives only the native code it needs. This avoids increasing the overall size of your app.

**Comment by beetlejesss** [comment]
Did you import all of the jniLibs directory into your project?

**Comment by zainkhalid91** [comment]
Yes I did. I imported just like the example said in the sdk. Everything works fine as well. But when uploading the bundle i am having this issue.

**Comment by zainkhalid91** [comment]
There were 3 jinLib that i imported
1- arm64-v8a
2- armabi-v7a
3- x86
These 3 were included in the sdk folder.

**Comment by dheimann** [comment]
You need to exclude the x86 jni lib when building for the play store. We include that architecture for some older devices, but that's basically legacy support at this point. If you only include the two arm libs it should clear that error

**Comment by zainkhalid91** [comment]
Okay thanks! 
@dheimann I will check it and report back.

**Comment by zainkhalid91** [comment]
@dheimann  Thanks you. It worked!
