### ISSUE TITLE
styles.xml - error: no resource found for theme Theme.AppCompat.Light.DarkActionBar

### ISSUE THREAD

**Issue by stfulton** [red5pro/streaming-android#31]
Using Eclipse, I've created a new Android Project From Existing Code.

It appears with a red x in the icon.

in `res/values/styles.xml` at line 4 there seems to be an error.

Line 4: `<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">`

```
error: Error retrieving parent for item: No resource found that matches the given name 
 'Theme.AppCompat.Light.DarkActionBar'.
```

(I've followed the most excellent tutorial on configuring Eclipse to work with the red5pro streaming server.)

I'm building for 4.2.2.  But I am new to Android!

Any ideas about this?

Thank you!

/stf

**Comment by HoldenMills** [comment]
It appears as though you may be using an old android SDK. Please make sure that you update Android SDK:
https://www.red5pro.com/docs/streaming/android/#upgrading-the-sdk-in-your-project   Not related to Red5 Pro.   http://stackoverflow.com/questions/18364682/theme-appcompat-light-darkactionbar-no-resource-found

**Comment by stfulton** [comment]
Hi Holden -

I'm sure I'm working with an updated version of the Android SDK.
Particularly since I recently downloaded Android Studio, which would have
updated the same SDK that Eclipse uses (I believe).

However, this link:
https://www.red5pro.com/docs/streaming/android/#upgrading-the-sdk-in-your-project

refers to updating the red5 streaming SDK (red5streaming.jar plus the
platform-specific source files in jibLibs) *not* the Android SDK.

Also, this is specific to Android Studio, whereas I'm working with
Eclipse.
(I realize Google wants everyone on Android Studio and they finished
supporting Eclipse ADT plugin almost a year ago).

Also, isnt this link is for *upgrading* from a *previous* version of the
streaming SDK?  (ie from a previous version to 1.0.0?)

I dont think this is even necessary now since GitHub examples are updated
with SDK v 1.0.0 of the SDK...

As to second link:
http://stackoverflow.com/questions/18364682/theme-appcompat-light-darkactionbar-no-resource-found

I'm pretty sure that I had the appcompat-v4 library referenced in this
project, but I actually blew it away in frustration in order to start over
again!

Regards,
Tim Fulton

**Comment by HoldenMills** [comment]
Hello Tim,

My apologies for not being more clear.  We have updated the Red5 Pro Server, and Android SDK (separate from Android Studio SDKs) to version 1.1.0.  With that in mind, you are right in that the example apps will have the updated SDK in them if you pull the changes.  I should have updated those documents before I sent them out to you.  Thank you for the feedback.

Please let me know if I can do anything else for you.

Thanks,
Holden

**Comment by jameskandau** [comment]
Add the theme at manifest file

**Comment by castasat** [comment]
1. Go to your project directory (or to `Project View`)
2. Find and open `.idea` directory
3. Remove `caches` and `libraries` directories   <-- this is essential
4. `Invalidate Caches / Restart`

**Comment by softronetMoitri** [comment]
Thank you @castasat it works for me after a day spent.

**Comment by jatinjain001** [comment]
This did not worked for me
