### ISSUE TITLE
Problem with secondscreen.jar

### ISSUE THREAD

**Issue by hugofreire** [red5pro/streaming-android#35]
Error:Execution failed for task ':app:compileArm64DebugJavaWithJavac'.
> java.io.FileNotFoundException: /Users/hugo/Downloads/streaming-android-master/app/libs/secondscreen.jar (No such file or directory)

What solution i have?

**Comment by phongbm** [comment]
I have a same proplem.

**Comment by beetlejesss** [comment]
Maybe try a build/clean project. That file has not been a dependency in this project in a long time.

**Comment by kcobra** [comment]
delete the dependency
