### ISSUE TITLE
Rotation problem in jwplayer

### ISSUE THREAD

**Issue by shankar667** [red5pro/streaming-android#43]
Hi,
Firstly many thanks for your sdk and red5pro-server it helpful in development and production . 
The sdk works great in android, but i am getting one of small issue, if possible please guide me.

ISSUE: On web RTMP streaming by JWPlayer is rotating in 90 deg, but it good in server, is there any solution to fix it?

**Comment by HoldenMills** [comment]
Hello!  Please try our HLS example: https://github.com/red5pro/android-streaming-testbed/blob/master/app/src/main/java/red5pro/org/testandroidproject/tests/PublishTest/PublishTest.java#L68  Please following this link and fill out all the

**Comment by shankar667** [comment]
Hello HoldenMills,
Thanks for replay, i tried the example as you given above URL but it still same issue.

**Comment by shankar667** [comment]
I will raise the ticket to support team, thank you for your support.
