### ISSUE TITLE
Continue publish stream onPause

### ISSUE THREAD

**Issue by shankar667** [red5pro/streaming-android#44]
Hi,
I like to run stream (publish) even `onPause` the app and i like to close only `onDestroy`,
but currently stream stopping when `onPause` called. Can you guide me how it will be resolve?

Logs onPause: 
`I/ACodec: [OMX.google.aac.encoder] Now Executing->Idle`
`I/ACodec: [OMX.google.aac.encoder] Now Idle->Loaded`
`I/ACodec: [OMX.google.aac.encoder] Now Loaded`
`I/ACodec:  [OMX.google.aac.encoder] Now uninitialized`
`V/ActivityThread: updateVisibility : ActivityRecord{226ea5e9 token=android.os.BinderProxy@c1b8604 {com.barkingdog/com.barkingdog.MainActivity}} show : false`

**Comment by HoldenMills** [comment]
Hi Shankar.  I have put your ticket into the queue on our support system and I shall respond to you as soon as I can.  Please be on the lookout for an e-mail from me.  For all future requests please submit them through this link: [https://red5pro.zendesk.com/hc/en-us/requests/new](https://red5pro.zendesk.com/hc/en-us/requests/new) Thanks and I will be in touch soon.
