### ISSUE TITLE
Low Fps...

### ISSUE THREAD

**Issue by developeralp** [red5pro/streaming-android#52]
hello,

im just trying red5pro-streaming android project.

i have installed latest red5pro server on my windows.

i have two test devices first one is mtk6589 (armeabi-v7a ; this one gives 10-12 fps , publishing stream)

second one is Qualcomm Snapdragon 617 MSM8952(arm64-v8a ; this one gives 12 - 13 fps)

How can i improve fps , any ideas ?

note : im publishing 720x480 video and with 1000x1024 bitrate.

**Comment by HoldenMills** [comment]
Hello,

I'm not sure what you mean by a 1000x1024 bitrate.  The bitrate should be a single number.  Please take a look at [this FAQ](https://red5pro.zendesk.com/hc/en-us/articles/216136218-Suggested-Bitrates-for-Streaming) where you can find suggested bitrates.  Increasing the bitrate should increase the fps.

**Comment by developeralp** [comment]
hello ,

sorry i wrote bitrate wrong..

i mean 1000x1024 as 1024 kbps...

i tried 750 kbps and 1024 kbps but fps still same.

**Comment by HoldenMills** [comment]
Are you trying to send a 360p (Resolution 640 x 360) video? This FAQ on [video quality](https://red5pro.zendesk.com/hc/en-us/articles/221298048-Video-Quality) may be useful as well:
