### ISSUE TITLE
is the product flavour section required?

### ISSUE THREAD

**Issue by jd-alexander** [red5pro/streaming-android#6]
I'm following this example and trying to apply it to a project Im working on but Im a bit confused because here product flavours are being used for the different architecture types and in the red5pro android app repository it's not being used. I am having an error when trying to build for my emulator so I'm wondering if product flavours can be removed.

**Comment by cameroninfrared5** [comment]
Hi Joel,

Checked in with my team and they said you can specify whatever you want to use there.

**Comment by jd-alexander** [comment]
Alright

**Comment by jd-alexander** [comment]
I was asking becaue i was wondering if i dont specify them then my app wouldnt be supported by some architectures. Is it a required for the jniLibs?

**Comment by cameroninfrared5** [comment]
Hi Joel,

I'll check in with my team with that one and get back to you.

**Comment by jd-alexander** [comment]
:+1:
