### ISSUE TITLE
CustomVideoSource

### ISSUE THREAD

**Issue by andrewCleverUA** [red5pro/streaming-android#60]
How can i use other resource in the CustomVideoSource?
you have Bitmap field in the CustomVideoSource but it isn't used

**Comment by HoldenMills** [comment]
@andrewCleverUA My apologies for the delay in getting back to you.  Could you please fill out a [support ticket](https://red5pro.zendesk.com/hc/en-us/requests/new) with your issue.  The ticket fields will provide us most of the info we need to look into your question.  If you could please describe your project from the user's point of view, that would help.
