### ISSUE TITLE
Why isn't the SDK distributed via Maven Central or JitPack.io?

### ISSUE THREAD

**Issue by jd-alexander** [red5pro/streaming-android#7]
Using one of these means for distribution wouild make it easier for developers to update when you make changes instead having to manually delete jar files and replace them.

**Comment by cameroninfrared5** [comment]
Hi Joel,

I'll run this by the team to get you an answer on this one.

**Comment by jd-alexander** [comment]
:+1:

**Comment by cameroninfrared5** [comment]
Hey Joel,

Checked in with my team this morning - and they think its an excellent idea! 

However, we're a pretty small team at the moment and currently in the process of building our SDKs using CI. Once thats all set we can start in with improving the deployment scenarios. Goal is most certainly for sooner than later though! 

Thanks very much for the feedback though, very much appreciated.

**Comment by jd-alexander** [comment]
awesome. Glad to help :+1:
